</div> <!--- end div: main --->
</div> <!--- end div: wrapper --->
<div id="footer">
	<div id="footer-right">
	Powered by <a href="http://www.jquery.com">jQuery</a>
	</div>
	Code generated by the <a href="http://skeleton.riaforge.org">Skeleton Site Creator</a>, developed by <a href="http://www.ajaxcf.com">Joe Danziger</a>.
</div>